use_frameworks!

platform :ios, '11.0'

target 'PageListKit_Example' do
  pod 'PageListKit', :path => '../'
  pod 'MJRefresh'
  target 'PageListKit_Tests' do
    inherit! :search_paths
    
    
  end
end
